### PR TITLE
[DNM]Issue#113

### PR DESCRIPTION
**Pull request by FrankApiyo**
Fixes: #113

### CODE REVIEW

**Comment by p-netm** [comment]
@FrankApiyo Please give the pr a better name and if possible write something about what this pr fixes.

**Comment by FrankApiyo** [comment]
This is not ready for a review yet.

**Comment by cKellyDesign** [comment]
@FrankApiyo is #113 the only issue being addressed in this PR?

**Comment by FrankApiyo** [comment]
> @FrankApiyo is #113 the only issue being addressed in this PR?

yes @cKellyDesign. The reason why react-html-parser was installed is because some of the text we need to show on the compartment home may need parts of it to be bold and I thought this would be a pragmatic approach to take.

**Comment by FrankApiyo** [comment]
> This is not ready for a review yet.

this is because this is something I need to ask @hmakandi

**Comment by cKellyDesign** [comment]
@FrankApiyo yeah using `react-html-parser` is better than dangerously setting, I'm only hesitant because it hasn't been maintained in a few years (https://github.com/wrakky/react-html-parser/releases) and it's using react/-dom `^16.0.0`. 

> because some of the text we need to show on the compartment home may need parts of it to be bold

This is a common scenario so we do need to have a solution for this so for now let's keep `react-html-parser`, it may even be worth forking to see if updating react breaks anything :)

**Comment by FrankApiyo** [comment]
@hmakandi @moshthepitt I'm going to close this as it's not required

**Pull request closed without merging**
