### PR TITLE
Miecd vietnam

### PR DESCRIPTION
**Pull request by FrankApiyo**
Resolves: #151

### CODE REVIEW

**Comment by moshthepitt** [comment]
@FrankApiyo what is pending here?

**Comment by FrankApiyo** [comment]
@moshthepitt what is pending here is re-basing this branch with master.

**Comment by moshthepitt** [comment]
@FrankApiyo could you please merge master into this? (Dont rebase i.e. dont rewrite history)

**Comment by FrankApiyo** [comment]
https://github.com/OpenSRP/opensrp-web/pull/192

**Pull request closed without merging**
