### PR TITLE
Add Child dux module

### PR DESCRIPTION
**Pull request by prodhan29**
- add dux file of childs.
- add test code for the child-dux module

### CODE REVIEW

**Comment by moshthepitt** [comment]
Is there a way to avoid repeating the code?

**Comment by prodhan29** [comment]
> Is there a way to avoid repeating the code?

these are the basic functionalities which are common to all dux module.  in the mock ui, i saw some filtering criteria different from each others. however @p-netm  requested to create separate reducers for each page. you may suggest some way to avoid improve

**Comment by p-netm** [comment]
> Is there a way to avoid repeating the code?

@moshthepitt @prodhan29 

I fear that further abstraction in an attempt to dry the code out, will result in a loss of semantics around the data handled by any of the dux modules, its is however still possible to do so.

**Comment by moshthepitt** [comment]
@p-netm @prodhan29 

Based on the premise that usually being DRY is better than not being DRY, I have some questions:

- Do you get all these households, clients, and children from the same OpenSRP endpoint?
- If you consider [households](https://github.com/OpenSRP/opensrp-web/blob/master/clients/core/src/store/ducks/clients.ts) and [clients](https://github.com/OpenSRP/opensrp-web/blob/master/clients/core/src/store/ducks/households.ts):
    - Is it possible to make the reducer function more DRY?  The action types are different but what you do after identifying them is identical
    - is it possible to make the selectors that do the same thing more DRY?
    - is it possible to use generic types to improve the DRYness of the interfaces and other types? I mean in the case of the actions you are already extending AnyAction, why not go further?

**Comment by p-netm** [comment]
>     * Do you get all these households, clients, and children from the same OpenSRP endpoint?

Yes, i did consider using a single reducer, the tradeoffs in terms of efficiency would be beteen speed and duplication of data, whereby having a single reducer would require filtering through thousands of records just to find say all clients of client_type child, or ANC, having different reducers for each would solve this but then getting data for households members would result in data duplication solely in the ducks slice containing household's members data.

>     * Is it possible to make the reducer function more DRY?  The action types are different but what you do after identifying them is identical

Yes, @prodhan29 ?

>     * is it possible to make the selectors that do the same thing more DRY?

yes, @prodhan29 ?

**Comment by prodhan29** [comment]
> 
> > ```
> > * Is it possible to make the reducer function more DRY?  The action types are different but what you do after identifying them is identical
> > ```
> 
> Yes, @prodhan29 ?
> 
> > ```
> > * is it possible to make the selectors that do the same thing more DRY?
> > ```
> 
> yes, @prodhan29 ?
i see both approach has their own trade off. please decide which would be better

**Pull request closed without merging**
